language: php
sudo: required

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

services:
  - docker

install:
  - composer install

before_script:
  - docker-compose -f docker/docker-compose.yml up -d
  - sh docker/waitForPostgres.sh

script:
  - vendor/bin/phpunit
